# nvidia base is from https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base

ARG BASE_IMAGE=nvcr.io/nvidia/l4t-ml:r32.4.3-py3
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
	python3-opencv ca-certificates \
    python3-pip python3-dev python3-setuptools \
    git \
    wget curl \
    sudo vim \
    ninja-build \
    cmake
RUN pip3 install Cython wheel

WORKDIR workspace

# PyCUDA
ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
RUN echo "$PATH" && echo "$LD_LIBRARY_PATH"
RUN pip3 install pycuda --verbose

# install dependencies
# See https://pytorch.org/ for other options if you use a different version of CUDA
RUN pip3 install tensorboard cmake   # cmake from apt-get is too old
RUN pip3 install torch==1.8 torchvision==0.9 -f https://download.pytorch.org/whl/cu101/torch_stable.html
RUN pip3 install 'git+https://github.com/facebookresearch/fvcore'

# Create user "developer" with sudo powers
RUN useradd -m developer && \
    usermod -aG sudo developer && \
    echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
    cp /root/.bashrc /home/developer/ && \
    mkdir /home/developer/data && \
    chown -R --from=root developer /home/developer

# Use C.UTF-8 locale to avoid issues with ASCII encoding
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

# install detectron2
RUN git clone https://github.com/hasbegun/detectron2 detectron2
# set FORCE_CUDA because during `docker build` cuda is not accessible
ENV FORCE_CUDA="1"

# This will by default build detectron2 for all common cuda architectures and take a lot more time,
# because inside `docker build`, there is no way to tell which architecture will be used.
ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"

RUN pip3 install -e detectron2

WORKDIR /home/developer/projects
ENV HOME /home/developer
ENV USER developer
USER developer
ENV PATH /home/developer/.local/bin:$PATH
# Avoid first use of sudo warning. c.f. https://askubuntu.com/a/22614/781671
RUN touch $HOME/.sudo_as_admin_successful
RUN echo "alias ..=\"cd ..\"" >> ~/.bashrc

# Set a fixed model cache directory.
ENV FVCORE_CACHE="/tmp"
WORKDIR /home/developer/projects/detectron2
